apiVersion: guard.security.knative.dev/v1alpha1
kind: Guardian
metadata:
  name: guard-vulnerable-app
  namespace: default
spec:
  control:
    alert: true
    auto: true
    block: true
    force: false
    learn: false
  learned:
    active: true
    envelop:
      completiontime: 2
      responsetime: 2
    pod:
      tcp4peers: null
      tcp6peers: null
      udp4peers: null
      udp6peers: null
      udplite4peers: null
      udplite6peers: null
    req:
      cip: null
      contentlength:
      - max: 0
        min: 0
      headers:
        kv:
          otherKeynames: null
          otherVals: null
          vals:
            Accept:
              digits: 7
              flags: 1073921792
              letters: 44
              nonreadables: 0
              schars: 23
              sequences: 33
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Accept-Encoding:
              digits: 0
              flags: 1024
              letters: 13
              nonreadables: 0
              schars: 2
              sequences: 7
              spaces: 2
              unicodeFlags: null
              unicodes: 0
            Accept-Language:
              digits: 4
              flags: 171008
              letters: 12
              nonreadables: 0
              schars: 10
              sequences: 18
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Cache-Control:
              digits: 1
              flags: 133120
              letters: 6
              nonreadables: 0
              schars: 2
              sequences: 5
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Sec-Ch-Ua:
              digits: 8
              flags: 8553474
              letters: 24
              nonreadables: 0
              schars: 18
              sequences: 22
              spaces: 4
              unicodeFlags: null
              unicodes: 0
            Sec-Ch-Ua-Mobile:
              digits: 1
              flags: 262144
              letters: 0
              nonreadables: 0
              schars: 1
              sequences: 2
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Sec-Ch-Ua-Platform:
              digits: 0
              flags: 2
              letters: 5
              nonreadables: 0
              schars: 2
              sequences: 3
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Sec-Fetch-Dest:
              digits: 0
              flags: 0
              letters: 8
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Sec-Fetch-Mode:
              digits: 0
              flags: 0
              letters: 8
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Sec-Fetch-Site:
              digits: 0
              flags: 0
              letters: 4
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Sec-Fetch-User:
              digits: 1
              flags: 262144
              letters: 0
              nonreadables: 0
              schars: 1
              sequences: 2
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Upgrade-Insecure-Requests:
              digits: 1
              flags: 0
              letters: 0
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            User-Agent:
              digits: 19
              flags: 8434816
              letters: 36
              nonreadables: 0
              schars: 17
              sequences: 33
              spaces: 12
              unicodeFlags: null
              unicodes: 0
            X-Forwarded-For:
              digits: 14
              flags: 5120
              letters: 0
              nonreadables: 0
              schars: 7
              sequences: 16
              spaces: 1
              unicodeFlags: null
              unicodes: 0
            X-Forwarded-Host:
              digits: 6
              flags: 4096
              letters: 9
              nonreadables: 0
              schars: 3
              sequences: 7
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            X-Forwarded-Port:
              digits: 2
              flags: 0
              letters: 0
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            X-Forwarded-Proto:
              digits: 0
              flags: 0
              letters: 4
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            X-Forwarded-Scheme:
              digits: 0
              flags: 0
              letters: 4
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            X-Real-Ip:
              digits: 7
              flags: 4096
              letters: 0
              nonreadables: 0
              schars: 3
              sequences: 7
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            X-Request-Id:
              digits: 22
              flags: 0
              letters: 18
              nonreadables: 0
              schars: 0
              sequences: 20
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            X-Scheme:
              digits: 0
              flags: 0
              letters: 4
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
      hopip: null
      mediatype:
        params:
          otherKeynames: null
          otherVals: null
          vals: null
        type:
          set:
          - none
      method:
        set:
        - GET
      proto:
        set:
        - HTTP/1.1
      qs:
        kv:
          otherKeynames: null
          otherVals: null
          vals: null
      url:
        segments:
        - max: 0
          min: 0
        val:
          digits: 0
          flags: 0
          letters: 0
          nonreadables: 0
          schars: 0
          sequences: 0
          spaces: 0
          unicodeFlags: null
          unicodes: 0
    reqbody:
      faults:
        set: []
      structured: null
      unstructured: null
    resp:
      contentlength:
      - max: 8
        min: 8
      headers:
        kv:
          otherKeynames: null
          otherVals: null
          vals:
            Content-Length:
              digits: 3
              flags: 0
              letters: 0
              nonreadables: 0
              schars: 0
              sequences: 1
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Content-Type:
              digits: 1
              flags: 174080
              letters: 17
              nonreadables: 0
              schars: 4
              sequences: 9
              spaces: 0
              unicodeFlags: null
              unicodes: 0
            Date:
              digits: 12
              flags: 17408
              letters: 9
              nonreadables: 0
              schars: 3
              sequences: 16
              spaces: 5
              unicodeFlags: null
              unicodes: 0
      mediatype:
        params:
          otherKeynames: null
          otherVals: null
          vals:
            charset:
              digits: 1
              flags: 2048
              letters: 3
              nonreadables: 0
              schars: 1
              sequences: 3
              spaces: 0
              unicodeFlags: null
              unicodes: 0
        type:
          set:
          - text/plain
          - text/html
    respbody:
      faults:
        set: []
      structured: null
      unstructured: null
  samples: 85
